const Strings = {
  Onboarding1_title: 'Connect people around \n the world',
  Onboarding1_subtitle: 'Stay in touch with your friends \n and family',
  Onboarding2_title: 'Stay safe and secure',
  Onboarding2_subtitle: 'Stay safe and secure with \n our app',
  Onboarding3_title: 'Stay up to date',
  Onboarding3_subtitle: 'Stay up to date with \n our app',
  Onboarding4_title: 'Welcome,Lets you in',
  Login_title: 'Login to your \n account',
  Login_forgot_password: 'Forgot Password?',
  Login_continueWith: 'or continue with',
  Login_signup: 'Don’t have an account?',
  Signup_title: 'Create to your \n Account',
  Signup_subtitle: 'Create your account to stay up to date',
  Signup_confirm_password: 'Confirm Password',
  Signup_login: 'Already have an account?',
  modal_takephoto: 'Take a photo',
  modal_choosefromlibrary: 'Choose from library',
  email_reset: 'Verification',
  sign_in: 'Sign In',
  sign_up: 'Sign Up',
  send_code: 'Send code',
  cancle: 'Cancle',
  email: ' Email',
  password: 'Password',
  verificatrion: 'Verification',
  f_name: 'First Name',
  l_name: 'Last Name',
  u_name: 'User Name',
  phone_no: 'Phone number',
  phone: 'Phone',
  next: 'Next',
};
export default Strings;
